/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "mta.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(OTRequest, OTRequest, AUTO)


PB_BIND(OTResponse, OTResponse, AUTO)


PB_BIND(MTASession, MTASession, 4)


PB_BIND(MTAResponse, MTAResponse, 4)


PB_BIND(Handshake, Handshake, AUTO)



